In [1]:
import cv2
import numpy as np
import scipy.stats
from mpmath import *


In [2]:
mask=cv2.imread('mask.jpg',1)
mask=cv2.cvtColor(mask,cv2.COLOR_BGR2GRAY)

pic=cv2.imread('train.jpg',1)
hsv=cv2.cvtColor(pic, cv2.COLOR_BGR2HSV)
hsv=hsv.astype(float)
pic=hsv.astype(float)

In [3]:
#cv2.imshow('H',hsv[:,:,0])
#cv2.imshow('S',hsv[:,:,1])
#cv2.imshow('V',hsv[:,:,2])

In [ ]:
cv2.imshow('H',mask)
cv2.waitKey(0)

In [4]:
np.unique(mask)

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  62,  63,  64,  65,  66,
        67,  68,  70,  71,  72,  73,  74,  75,  76,  77,  78,  79,  82,
        83,  84,  85,  86,  87,  88,  89,  90,  93,  94,  95,  96,  97,
        98,  99, 100, 101, 102, 105, 106, 107, 108, 109, 110, 111, 112,
       113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125,
       126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138,
       139, 140, 141, 142, 143, 145, 146, 147, 148, 149, 150, 152, 153,
       154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166,
       167, 168, 170, 171, 172, 173, 175, 177, 178, 179, 180, 181, 182,
       183, 184, 185, 186, 187, 188, 189, 190, 192, 193, 194, 19

In [7]:
def get_pixels(img,mask):
    rows,cols=mask.shape
    ncoin=np.sum(mask>128)
    ndesk=np.sum(mask<=128)
    print(mask.shape)
    coin =img[(mask>128).nonzero()]
    desk =img[(mask<=128).nonzero()]
    print(coin)
    print(desk)
    return [ncoin, ndesk]

In [8]:
get_pixels(hsv,mask)

(960, 1280)
[[103.  27. 151.]
 [104.  25. 156.]
 [105.  22. 160.]
 ...
 [ 10.   6. 124.]
 [  8.   8. 128.]
 [  0.   8. 130.]]
[[ 12.  29. 130.]
 [ 10.  29. 132.]
 [  9.  27. 133.]
 ...
 [ 90.   8. 134.]
 [ 83.   8. 132.]
 [ 90.   6. 130.]]


[47162, 1181638]

In [13]:
len((mask>128).nonzero())

2

In [11]:
(pic > 128).nonzero()

(array([  0,   0,   0, ..., 959, 959, 959], dtype=int64),
 array([   0,    1,    2, ..., 1277, 1278, 1279], dtype=int64),
 array([2, 2, 2, ..., 2, 2, 2], dtype=int64))

In [10]:
mask=cv2.imread('mask.jpg',1)

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  62,  63,  64,  65,  66,
        67,  68,  70,  71,  72,  73,  74,  75,  76,  77,  78,  79,  82,
        83,  84,  85,  86,  87,  88,  89,  90,  93,  94,  95,  96,  97,
        98,  99, 100, 101, 102, 105, 106, 107, 108, 109, 110, 111, 112,
       113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125,
       126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138,
       139, 140, 141, 142, 143, 145, 146, 147, 148, 149, 150, 152, 153,
       154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166,
       167, 168, 170, 171, 172, 173, 175, 177, 178, 179, 180, 181, 182,
       183, 184, 185, 186, 187, 188, 189, 190, 192, 193, 194, 19